apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webhook-dpl
  labels:
    app: webhook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webhook
        name: webhook-pod
    spec:
      containers:
      - name: pullrequest-webhook
        image: lucassabreu/buddy-works-pullrequest-webhook:latest
        imagePullPolicy: Always
        env:
          - name: WORKSPACE
            value: lucassabreu
          - name: PROJECT
            value: k8s-pr-envs
          - name: PIPELINE_NAME
            value: Close Review
          - name: BUDDY_TOKEN
            value: __BUDDY_TOKEN__
        ports:
        - name: web-port
          containerPort: 8080
---
apiVersion: "v1"
kind: Service
metadata:
  name: webhook-svc
  labels:
    app: webhook
spec:
  ports:
    - port: 80
      targetPort: "web-port"
      protocol: TCP
  selector:
    name: webhook-pod
    app: webhook
---
apiVersion: v1
kind: Route
metadata:
  name: webhook
  labels:
    app: webhook
spec:
  host: pullrequest-webhook-github-k8s-pr-envs.getup.io
  to:
    kind: Service
    name: webhook-svc

